
CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM" (
    "product_sold" VARCHAR(12),
    total_items INTEGER
);


CREATE OR REPLACE PUMP "STREAM_PUMP" AS INSERT INTO "DESTINATION_SQL_STREAM"
SELECT STREAM
    "product_sold",
    SUM("num_items")
FROM "SOURCE_SQL_STREAM_001"
GROUP BY 
    "product_sold",
    FLOOR(("SOURCE_SQL_STREAM_001".ROWTIME - TIMESTAMP '1970-01-01 00:00:00') SECOND / 10 TO SECOND)
ORDER BY
    FLOOR(("SOURCE_SQL_STREAM_001".ROWTIME - TIMESTAMP '1970-01-01 00:00:00') SECOND / 10 TO SECOND), 
    SUM("num_items") DESC;